In [3]:
import numpy as np
board = 100
dice=6
state = board+1+(2*dice)


snakes_ladders = [[1, 38], [4, 14], [9, 31], [21, 42], [28, 84], [36, 44], [51, 67], [71, 91], [80, 100], [16, 6], [47, 26], [49, 11], [56, 53], [62, 19],[64, 60], [87, 24], [93, 73], [95, 75], [98, 78]]

def transition_matrix1(dice, board, state):
    M = np.zeros((state, state), dtype=float)
    for i in range(0, state):
        for j in range(1, state):
            if j <= (2*dice) and i <= board-(2*dice):
                M[i, j+i-1] = (dice - abs(j-(dice+1)))/(dice*dice)
            if i >= board-(2*dice):
                if i < board and (state-j)<=(2*dice):
                    M[i, state-j+i-1] = (dice - abs((state-j)-(dice+1)))/(dice*dice)
            """if i >= board-(2*dice) :
                #M[i, i] = ((dice-board)+i)/dice
                if i < board  and state-j<=2*dice:
                    M[i, state-j+i] = (dice - abs(j-(dice+1)))/(dice*dice)"""
            if i>=board:
                M[i,i]=1
    return M
# transition matrix with  snake and ladder ####ladders=0,


def snake_ladder(M, snakes, state):
    for i in range(0, state):
        for snake in snakes:
            if i < snake[0]:
                M[i, snake[1]] = M[i, snake[1]] + M[i, snake[0]]
            M[snake[0], i] = 0
            M[i, snake[0]] = 0
    return M


# calculating length of the game based on fundamental form
def fundamental_form(M):
    Q = M[:-((2*dice)+1), :-((2*dice)+1)]
    N = np.linalg.inv(np.identity(len(Q))-Q)
    length = np.matmul(N, np.ones((len(N), 1)))
    return length[0][0]
def expectation():
    print(fundamental_form(snake_ladder(
            transition_matrix1(dice, board, state), snakes_ladders, state)))
#expectation()


In [4]:
#print(transition_matrix1(dice, board, state))
expectation()


19.747206117926744


In [5]:
import numpy

In [11]:
np.random.choice(100,size=2,replace=False)

array([95, 88])

In [12]:
import math

In [13]:
print(math.factorial(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


In [14]:
x=(math.factorial(100))/((2**50)*math.factorial(50))

In [1]:
import os,sys
dir_path=os.path.dirname("C:\\Users\\edway\\Desktop\\maths\\thesis\\algo_thesis\\game")
sys.path.append(dir_path)
import numpy as np
from game.harmoni import Harmonic

class Markov(object):
    snakes_ladders = [[1, 38], [4, 14], [9, 31], [21, 42], [28, 84], [36, 44], [51, 67], [71, 91], [80, 100], [
        16, 6], [47, 26], [49, 11], [56, 53], [62, 19], [64, 60], [87, 24], [93, 73], [95, 75], [98, 78]]

    def __init__(self, dice, board):
        self.dice = dice
        self.board = board
        self.state = board+1
        self.dist=[]
        nth=Harmonic(self.dice)
        
        for d in range(1,self.dice+1):
            self.dist.append(1/(d*nth.harmonic()))
        print(sum(self.dist))

    def bmatrix(self, a):
        """Returns a LaTeX bmatrix

        :a: numpy array
        :returns: LaTeX bmatrix as a string
        """
        if len(a.shape) > 2:
            raise ValueError('bmatrix can at most display two dimensions')
        lines = str(a).replace('[', '').replace(']', '').splitlines()
        rv = [r'\left(\begin{array}{*{17}c}']
        rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
        rv += [r'\end{array}\right)']
        return '\n'.join(rv)
    
    def transition_matrix2(self):
        self.state=self.state + self.dice - 1
        M = np.zeros((self.state, self.state), dtype=float)
        for i in range(0, self.state):
            for j in range(1, self.state):
                if j <= self.dice and i <= (self.board - self.dice):
                    M[i, j+i] = 1/self.dice
                if i >= (self.board-self.dice):
                    if i < self.board  and (self.state-j)<=self.dice:
                        M[i, self.state-j+i] = 1/self.dice
                if i>=self.board:
                    M[i,i]=1
        return M
    
    #more tha one dice
    def transition_matrix3(self):
        acc=0
        Tdice=2*self.dice
        M=np.zeros((self.state,self.state),dtype=float)
        for i in range(0,self.state):
            for j in range(1,self.state):
                if j <= (Tdice) and i <= (self.board):
                    if j+i <= len(M):
                        M[i,i+j-1]=(self.dice - abs(j-(self.dice+1)))/(self.dice*self.dice)
                """if i > self.board-Tdice and i<=self.board:
                    if j+i <= len(M):
                        M[i, j+i-1]=(self.dice - abs(j-(self.dice+1)))/(self.dice*self.dice)"""
        for i in range(0,self.state):
            for j in range(1,self.state):
                acc += M[i,j]
            M[i,i]=1-acc
            acc=0
        return M
    def transition_matrix1(self):
        M = np.zeros((self.state, self.state), dtype=float)
        for i in range(0, self.state):
            for j in range(1, self.state):
                if j <= (self.dice) and i <= (self.board-self.dice):
                    M[i, j+i] = 1/self.dice
                if i >= self.board-self.dice:
                    M[i, i] = ((self.dice-self.board)+i)/self.dice
                    if j+i < len(M):
                        M[i, j+i] = 1/self.dice
        
        return M
    def transition_harmonic(self):
        acc=0
        M = np.zeros((self.state, self.state), dtype=float)
        for i in range(0, self.state):
            for j in range(1, self.state):
                if j <= (self.dice) and i <= (self.board-self.dice):
                    M[i, j+i] = self.dist[j-1]
                if i>=self.board - self.dice:
                    if j+i<len(M):
                        M[i,j+i]=self.dist[j-1]
        for i in range(0,self.state):
            for j in range(1,self.state):
                acc += M[i,j]
            M[i,i]=1-acc
            acc=0
        return M
                
    def snake_ladder(self, M, snakes):
        for i in range(0, self.state):
            for j in range(0, self.state):
                for snake in snakes:
                    if j == snake[0]:
                        x = M[i, snake[0]]
                        M[snake[0]] = 0
                        M[i, snake[1]] = M[i, snake[1]] + x
                        M[i, snake[0]] = 0

        return M
    
    def fundamental_form(self, M):
        Q = M[:-1, :-1]
        N = np.linalg.inv(np.identity(len(Q)) - Q)
        length = np.matmul(N, np.ones((len(N), 1)))
        # print(self.bmatrix(length))
        return length[0][0]


In [1]:
import os,sys
dir_path=os.path.dirname("C:\\Users\\edway\\Desktop\\maths\\thesis\\algo_thesis\\game")
sys.path.append(dir_path)
from markov_og import Markov
from game.snake_ladder import Snakes
from pandas import DataFrame
import ast
lists=[]
avg=[]

uu=[[4,13],[14,7],[6,3]]

snake=Snakes(0,0)
markov=Markov(100,100)
trans1=markov.transition_harmonic()
print(trans1)
du=DataFrame(trans1)
#sl=markov.snake_ladder(trans1,uu)
#df=DataFrame(sl)
#print(sl)
#result=markov.fundamental_form(sl)
#print(result)


[[0.         0.19277564 0.09638782 ... 0.0019671  0.00194723 0.00192776]
 [0.         0.00192776 0.19277564 ... 0.00198738 0.0019671  0.00194723]
 [0.         0.         0.00387499 ... 0.00200808 0.00198738 0.0019671 ]
 ...
 [0.         0.         0.         ... 0.71083655 0.19277564 0.09638782]
 [0.         0.         0.         ... 0.         0.80722436 0.19277564]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [2]:

du

0         1         2         3    4         5    6         7         8   \
0   0.0  0.295794  0.147897  0.147897  0.0  0.059159  0.0  0.063384  0.036974   
1   0.0  0.018487  0.295794  0.207056  0.0  0.073949  0.0  0.072052  0.042256   
2   0.0  0.000000  0.038207  0.369743  0.0  0.098598  0.0  0.083808  0.049299   
3   0.0  0.000000  0.000000  0.157933  0.0  0.147897  0.0  0.100839  0.059159   
4   0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.000000   
5   0.0  0.000000  0.000000  0.295794  0.0  0.106738  0.0  0.180763  0.098598   
6   0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.000000   
7   0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.205464  0.295794   
8   0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.049299  0.196074   
9   0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.059159  0.000000   
10  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.073949  0.000000   
11  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.098598  0.000000   
12  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.147897  0.000000   
13  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.295794  0.000000   
14  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.000000   
15  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.000000   
16  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.000000  0.000000   

          9         10        11        12        13   14        15        16  
0   0.032866  0.029579  0.026890  0.024650  0.096702  0.0  0.019720  0.018487  
1   0.036974  0.032866  0.029579  0.026890  0.123248  0.0  0.021128  0.019720  
2   0.042256  0.036974  0.032866  0.029579  0.174787  0.0  0.022753  0.021128  
3   0.049299  0.042256  0.036974  0.032866  0.325374  0.0  0.024650  0.022753  
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  
5   0.073949  0.059159  0.049299  0.042256  0.036974  0.0  0.029579  0.026890  
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  
7   0.147897  0.098598  0.073949  0.059159  0.049299  0.0  0.036974  0.032866  
8   0.295794  0.147897  0.098598  0.073949  0.059159  0.0  0.042256  0.036974  
9   0.233048  0.295794  0.147897  0.098598  0.073949  0.0  0.049299  0.042256  
10  0.000000  0.275304  0.295794  0.147897  0.098598  0.0  0.059159  0.049299  
11  0.000000  0.000000  0.324603  0.295794  0.147897  0.0  0.073949  0.059159  
12  0.000000  0.000000  0.000000  0.383762  0.295794  0.0  0.098598  0.073949  
13  0.000000  0.000000  0.000000  0.000000  0.457711  0.0  0.147897  0.098598  
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  0.000000  
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.704206  0.295794  
16  0.000000  0.000000  0.000000  0.000000  0.000000  0.0  0.000000  1.000000

In [7]:
df[14]


0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    0.0
13    0.0
14    0.0
15    0.0
16    0.0
Name: 14, dtype: float64

In [3]:
trans1

array([[0.        , 0.29579419, 0.1478971 , 0.1478971 , 0.        ,
        0.05915884, 0.        , 0.06338447, 0.03697427, 0.03286602,
        0.02957942, 0.02689038, 0.02464952, 0.09670195, 0.        ,
        0.01971961, 0.01848714],
       [0.        , 0.01848714, 0.29579419, 0.20705593, 0.        ,
        0.07394855, 0.        , 0.07205243, 0.04225631, 0.03697427,
        0.03286602, 0.02957942, 0.02689038, 0.12324758, 0.        ,
        0.02112816, 0.01971961],
       [0.        , 0.        , 0.03820675, 0.36974274, 0.        ,
        0.09859806, 0.        , 0.08380835, 0.04929903, 0.04225631,
        0.03697427, 0.03286602, 0.02957942, 0.17478748, 0.        ,
        0.0227534 , 0.02112816],
       [0.        , 0.        , 0.        , 0.15793297, 0.        ,
        0.1478971 , 0.        , 0.10083893, 0.05915884, 0.04929903,
        0.04225631, 0.03697427, 0.03286602, 0.32537361, 0.        ,
        0.02464952, 0.0227534 ],
       [0.        , 0.        , 0.        , 0.      

In [1]:
import os,sys
dir_path=os.path.dirname("C:\\Users\\edway\\Desktop\\maths\\thesis\\algo_thesis\\game")
sys.path.append(dir_path)
import numpy as np
from harmoni import Harmonic
from result import result
snakes = [[1, 38], [4, 14], [9, 31], [21, 42], [28, 84], [36, 44], [51, 67], [71, 91], [80, 100], [
    16, 6], [47, 26], [49, 11], [56, 53], [62, 19], [64, 60], [87, 24], [93, 73], [95, 75], [98, 78]]
dist = []
countlist=[]
nth = Harmonic(100)
for d in range(1, 101):
    dist.append(1.0/(d*nth.harmonic()))
u=[]
for o in range(0,100):
    u.append(o+1)

def simuharmonic(dice, sl):
    
    count = 0
    path = []
    token = 0
    while token < 100:
        roll = np.random.choice(range(1,101), size=1, p=dist, replace=False)[0]
        token += roll
        count += 1
        if token > 100:
            token -= roll
            count += 1
        for trans in sl:
            if token == trans[0]:
                token = trans[1]
                break
        path.append(token)
    return [count, path]
for i in range(0,10000):
    countlist.append(simuharmonic(100,snakes))
re = result(countlist)
re.results()

ModuleNotFoundError: No module named 'harmoni'